### ISSUE TITLE
URL not matching

### ISSUE THREAD

**Issue by mosheavni** [rmagatti/gx-extended.nvim#16]
because of this line:
https://github.com/rmagatti/gx-extended.nvim/blob/e5fb1b719126c30110ee5b642f79c3eb79c88571/lua/gx-extended/extensions/no-protocol-urls.lua#L14
this url:
https://github.com/bitnami/containers/tree/main/bitnami/mongodb#creating-a-user-and-database-on-first-run

is not matching and not opening. by removing this if, everything works.

**Comment by rmagatti** [comment]
Should be fixed now
